DROP DATABASE Odds;
CREATE DATABASE Odds DEFAULT CHARACTER SET utf8;
USE Odds;

# 博彩公司表
CREATE TABLE Companies (OID int PRIMARY KEY AUTO_INCREMENT, CompanyId VARCHAR(8) NOT NULL, CompanyDetail VARCHAR(128) NOT NULL, Nation VARCHAR(32) NOT NULL);

# 球队表
CREATE TABLE Teams (OID int PRIMARY KEY AUTO_INCREMENT, TeamId VARCHAR(16) NOT NULL, TeamDetail VARCHAR(32) NOT NULL, TeamCNDetail VARCHAR(128) NULL, Alias VARCHAR(128) NULL);

# 联赛表
CREATE TABLE Leagues(OID int PRIMARY KEY AUTO_INCREMENT, LeagueId VARCHAR(16) NOT NULL, LeagueCNDetail VARCHAR(128) NOT NULL);

# 比赛结果表
CREATE TABLE Matches(OID int PRIMARY KEY AUTO_INCREMENT, HomeTeamId VARCHAR(16) NOT NULL, AwayTeamId VARCHAR(16) NOT NULL, Score VARCHAR(16) NOT NULL, LeagueId VARCHAR(16) NOT NULL, MatchTime VARCHAR(16) NOT NULL, MatchRound VARCHAR(8) NOT NULL, HalfScore VARCHAR(16) NULL, HomeLastRank VARCHAR(16) NULL, AwayLastRank VARCHAR(16) NULL, LinkIndex VARCHAR(32) NOT NULL);

# 欧赔表
CREATE TABLE MatchEuropeanOdds_1129(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_90(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_432(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_81(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_517(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_115(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_474(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_499(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_82(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_422(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_80(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_450(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_60(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_110(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_545(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_177(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_370(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_4(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_97(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_104(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_649(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_158(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_70(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_71(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_88(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_9(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_255(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_173(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_281(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_18(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchEuropeanOdds_16(OID int PRIMARY KEY AUTO_INCREMENT, VictoryOdd VARCHAR(16) NULL, DrawOdd VARCHAR(16) NULL, LoseOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);


# 亚赔表
CREATE TABLE MatchAsianOdds_1129(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_90(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_432(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_81(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_517(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_115(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_474(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_499(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_82(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_422(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_80(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_450(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_60(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_110(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_545(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_177(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_370(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_4(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_97(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_104(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_649(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_158(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_70(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_71(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_88(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_9(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_255(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_173(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_281(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_18(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);
CREATE TABLE MatchAsianOdds_16(OID int PRIMARY KEY AUTO_INCREMENT, HomeOdd VARCHAR(16) NULL, Standard VARCHAR(16) NULL, AwayOdd VARCHAR(16) NULL, ReturnRate VARCHAR(8) NULL, ReleaseTime VARCHAR(16) NULL, StartFlag TINYINT(1) NOT NULL, EndFlag TINYINT(1) NOT NULL, SecondStartFlag TINYINT(1) NULL, MatchId int NOT NULL);


# 博彩公司数据
INSERT INTO Companies VALUES ( 1, '1129', '竞彩官方', '中国');
INSERT INTO Companies VALUES ( 2, '90', '易胜博', '安提瓜和巴布达');
INSERT INTO Companies VALUES ( 3, '432', '香港马会', '中国香港');
INSERT INTO Companies VALUES ( 4, '81', '伟德', '直布罗陀');
INSERT INTO Companies VALUES ( 5, '517', '明陆', '菲律宾');
INSERT INTO Companies VALUES ( 6, '115', '威廉希尔', '英国');
INSERT INTO Companies VALUES ( 7, '474', '利记Sbobet', '英国');
INSERT INTO Companies VALUES ( 8, '499', '金宝博', '马恩岛');
INSERT INTO Companies VALUES ( 9, '82', '立博', '英国');
INSERT INTO Companies VALUES ( 10, '422', '博天堂', '瓦努阿图');

INSERT INTO Companies VALUES ( 11, '80', '澳门', '中国');
INSERT INTO Companies VALUES ( 12, '450', 'TOTO', '荷兰');
INSERT INTO Companies VALUES ( 13, '60', 'STS', '波兰');
INSERT INTO Companies VALUES ( 14, '110', 'SNAI', '意大利');
INSERT INTO Companies VALUES ( 15, '545', '皇冠SB', '澳大利亚');
INSERT INTO Companies VALUES ( 16, '177', 'Pinnacle', '荷兰');
INSERT INTO Companies VALUES ( 17, '370', 'Oddset', '德国');
INSERT INTO Companies VALUES ( 18, '4', 'Nordicbet', '马恩岛');
INSERT INTO Companies VALUES ( 19, '97', 'Nike', '斯洛伐克');
INSERT INTO Companies VALUES ( 20, '104', 'Interwetten', '塞浦路斯');

INSERT INTO Companies VALUES ( 21, '649', 'IBCBET', '哥斯达黎加');
INSERT INTO Companies VALUES ( 22, '158', 'Gamebookers', '安提瓜和巴布达');
INSERT INTO Companies VALUES ( 23, '70', 'Expekt', '瑞典');
INSERT INTO Companies VALUES ( 24, '71', 'Eurobet', '英国');
INSERT INTO Companies VALUES ( 25, '88', 'Coral', '英国');
INSERT INTO Companies VALUES ( 26, '9', 'Centrebet', '澳大利亚');
INSERT INTO Companies VALUES ( 27, '255', 'bwin', '奥地利');
INSERT INTO Companies VALUES ( 28, '173', 'bet-at-home', '马耳他');
INSERT INTO Companies VALUES ( 29, '281', 'bet 365', '英国');
INSERT INTO Companies VALUES ( 30, '18', '12BET', '菲律宾');

INSERT INTO Companies VALUES ( 31, '16', '10BET', '英国');

# 联赛数据
INSERT INTO Leagues VALUES ( 1, '36', '英超');
INSERT INTO Leagues VALUES ( 2, '37', '英冠');
INSERT INTO Leagues VALUES ( 3, '39', '英甲');
INSERT INTO Leagues VALUES ( 4, '35', '英乙');
INSERT INTO Leagues VALUES ( 5, '31', '西甲');
INSERT INTO Leagues VALUES ( 6, '33', '西乙');
INSERT INTO Leagues VALUES ( 7, '8', '德甲');
INSERT INTO Leagues VALUES ( 8, '9', '德乙');
INSERT INTO Leagues VALUES ( 9, '34', '意甲');
INSERT INTO Leagues VALUES ( 10, '40', '意乙');

INSERT INTO Leagues VALUES ( 11, '11', '法甲');
INSERT INTO Leagues VALUES ( 12, '12', '法乙');
INSERT INTO Leagues VALUES ( 13, '16', '荷甲');
INSERT INTO Leagues VALUES ( 14, '17', '荷乙');
INSERT INTO Leagues VALUES ( 15, '23', '葡超');
INSERT INTO Leagues VALUES ( 16, '157', '葡甲');
INSERT INTO Leagues VALUES ( 17, '29', '苏超');
INSERT INTO Leagues VALUES ( 18, '150', '苏冠');
INSERT INTO Leagues VALUES ( 19, '4', '巴甲');
INSERT INTO Leagues VALUES ( 20, '358', '巴乙');

INSERT INTO Leagues VALUES ( 21, '2', '阿甲');
INSERT INTO Leagues VALUES ( 22, '423', '阿乙');
INSERT INTO Leagues VALUES ( 23, '21', '美职联');
INSERT INTO Leagues VALUES ( 24, '60', '中超');
INSERT INTO Leagues VALUES ( 25, '61', '中甲');
INSERT INTO Leagues VALUES ( 26, '25', '日职联');
INSERT INTO Leagues VALUES ( 27, '284', '日职乙');

# 球队数据
INSERT INTO Teams VALUES( 1, '310', 'New York Red Bulls', '纽约红牛', '紐約紅牛');
INSERT INTO Teams VALUES( 2, '311', 'LA Galaxy', '洛杉矶银河', '洛杉磯銀河');
INSERT INTO Teams VALUES( 3, '314', 'DC United', '华盛顿联', '華盛頓聯隊');
INSERT INTO Teams VALUES( 4, '316', 'New England Revolution', '新英格兰革命', '新英倫革命');
INSERT INTO Teams VALUES( 5, '318', 'FC Kansas City', '肯萨斯竞技', '肯薩斯體育會');
INSERT INTO Teams VALUES( 6, '319', 'Chicago Fire', '芝加哥火焰', '芝加哥火燄');
INSERT INTO Teams VALUES( 7, '321', 'FC Dallas', '达拉斯FC', 'FC達拉斯');
INSERT INTO Teams VALUES( 8, '323', 'Colorado Rapids', '科罗拉多急流', '科羅拉多急流');
INSERT INTO Teams VALUES( 9, '326', 'San Jose Earthquakes', '圣何塞地震', '聖荷西地震');
INSERT INTO Teams VALUES( 10, '327', 'Columbus Crew', '哥伦布机员', '哥倫布機員');
INSERT INTO Teams VALUES( 11, '2071', 'Real Salt Lake', '皇家盐湖城', '皇家鹽湖城');
INSERT INTO Teams VALUES( 12, '4073', 'Houston Dynamo', '休斯敦迪纳摩', '侯斯頓戴拿模');
INSERT INTO Teams VALUES( 13, '5345', 'Toronto FC', '多伦多FC', '多倫多FC');
INSERT INTO Teams VALUES( 14, '5526', 'Seattle Sounders', '西雅图音速', '西雅圖海灣者');
INSERT INTO Teams VALUES( 15, '5528', 'Minnesota United FC', '明尼苏达联', '明尼蘇達聯');
INSERT INTO Teams VALUES( 16, '5530', 'Montreal Impact', '蒙特利尔冲击', '蒙特利爾衝擊');
INSERT INTO Teams VALUES( 17, '5533', 'Vancouver Whitecaps', '温哥华白帽', '溫哥華白帽');
INSERT INTO Teams VALUES( 18, '5555', 'Portland Timbers', '波特兰伐木者', '波特蘭伐木者');
INSERT INTO Teams VALUES( 19, '13541', 'Philadelphia Union', '费城联合', '費城聯');
INSERT INTO Teams VALUES( 20, '16669', 'Orlando City', '奥兰多城', '奧蘭多城');
INSERT INTO Teams VALUES( 21, '23297', 'New York City Football Club', '纽约城', '紐約城');
INSERT INTO Teams VALUES( 22, '31761', 'Atlanta United', '亚特兰大联', '亞特蘭大聯');
INSERT INTO Teams VALUES( 23, '36878', 'Los Angeles FC', '洛杉矶FC', '洛杉磯FC');
INSERT INTO Teams VALUES( 24, '178', 'Albirex Niigata', '新泻天鹅', '新潟天鵝');
INSERT INTO Teams VALUES( 25, '184', 'Oita Trinita', '大分三神', '大分三神');
INSERT INTO Teams VALUES( 26, '199', 'JEF United Ichihara Chiba', '千叶市原', '千葉市原');
INSERT INTO Teams VALUES( 27, '200', 'Tokyo Verdy', '东京绿茵', '東京綠茵');
INSERT INTO Teams VALUES( 28, '1547', 'Avispa Fukuoka', '福冈黄蜂', '福岡黃蜂');
INSERT INTO Teams VALUES( 29, '1988', 'Omiya Ardija', '大宫松鼠', '大宮松鼠');
INSERT INTO Teams VALUES( 30, '3162', 'Ventforet Kofu', '甲府风林', '甲府風林');
INSERT INTO Teams VALUES( 31, '3163', 'Kyoto Sanga', '京都不死鸟', '京都不死鳥');
INSERT INTO Teams VALUES( 32, '3165', 'Montedio Yamagata', '山形山神', '山形山神');
INSERT INTO Teams VALUES( 33, '3194', 'Mito Hollyhock', '水户蜀葵', '水戶蜀葵');
INSERT INTO Teams VALUES( 34, '3196', 'Tokushima Vortis', '德岛漩涡', '德島漩渦');
INSERT INTO Teams VALUES( 35, '3415', 'Yokohama FC', '横滨FC', 'FC橫濱');
INSERT INTO Teams VALUES( 36, '4024', 'Ehime FC', '爱嫒FC', 'FC愛媛');
INSERT INTO Teams VALUES( 37, '4904', 'Tochigi SC', '枥木SC', '櫪木SC');
INSERT INTO Teams VALUES( 38, '7540', 'FC Gifu', 'FC岐阜', 'FC岐阜');
INSERT INTO Teams VALUES( 39, '7541', 'Roasso Kumamoto', '熊本深红', '熊本深紅');
INSERT INTO Teams VALUES( 40, '9024', 'Fagiano Okayama', '冈山绿雉', '岡山綠雉');
INSERT INTO Teams VALUES( 41, '9025', 'Zweigen Kanazawa FC', '金泽', '金澤聯隊');
INSERT INTO Teams VALUES( 42, '9030', 'Matsumoto Yamaga FC', '松本山雅', '松本山雅');
INSERT INTO Teams VALUES( 43, '10035', 'Machida Zelvia', '町田泽维亚', '町田澤維亞');
INSERT INTO Teams VALUES( 44, '11943', 'Renofa Yamaguchi', '山口雷法', '山口雷法');
INSERT INTO Teams VALUES( 45, '11944', 'Kamatamare Sanuki', '赞岐', '讚岐烏冬');
INSERT INTO Teams VALUES( 46, '233', 'Roda JC', '罗达JC', '洛達');
INSERT INTO Teams VALUES( 47, '239', 'NEC Nijmegen', '尼美根', 'NEC尼美根');
INSERT INTO Teams VALUES( 48, '241', 'RKC Waalwijk', '瓦尔韦克', 'RKC華域克');
INSERT INTO Teams VALUES( 49, '250', 'FC Twente Enschede', '特温特', '川迪');
INSERT INTO Teams VALUES( 50, '258', 'Den Bosch', '邓伯什', '丹博斯治');
INSERT INTO Teams VALUES( 51, '273', 'Sparta Rotterdam', '鹿特丹斯巴达', '鹿特丹斯巴達');
INSERT INTO Teams VALUES( 52, '275', 'Helmond Sport', '赫尔蒙德', '靴蒙特');
INSERT INTO Teams VALUES( 53, '279', 'SC Telstar', '特尔斯达', '泰斯達');
INSERT INTO Teams VALUES( 54, '280', 'Go Ahead Eagles', '前进之鹰', '伊高斯');
INSERT INTO Teams VALUES( 55, '281', 'FC Oss', '奥斯', '奧斯');
INSERT INTO Teams VALUES( 56, '287', 'Dordrecht', '多德勒支', '多德勒支');
INSERT INTO Teams VALUES( 57, '288', 'SC Cambuur', '坎布尔', '甘堡爾');
INSERT INTO Teams VALUES( 58, '290', 'MVV Maastricht', '马斯特里赫特', '馬斯特里赫特');
INSERT INTO Teams VALUES( 59, '415', 'Volendam', '福伦丹', '華倫丹');
INSERT INTO Teams VALUES( 60, '1092', 'FC Eindhoven', 'FC埃因霍温', 'FC燕豪芬');
INSERT INTO Teams VALUES( 61, '2596', 'Almere City FC', '阿尔梅勒城', '阿梅爾城');
INSERT INTO Teams VALUES( 62, '7214', 'Jong Ajax (Youth)', '阿贾克斯青年队', '阿積士青年隊');
INSERT INTO Teams VALUES( 63, '7219', 'FC Utrecht (Youth)', '乌德勒支青年队', '烏德勒支青年隊');
INSERT INTO Teams VALUES( 64, '7416', 'AZ Alkmaar (Youth)', '阿尔克马尔青年队', '艾克馬亞青年隊');
INSERT INTO Teams VALUES( 65, '7580', 'Jong PSV Eindhoven (Youth)', '埃因霍温青年队', 'PSV燕豪芬青年隊');
INSERT INTO Teams VALUES( 66, '90', 'Arminia Bielefeld', '比勒菲尔德', '比勒費爾德');
INSERT INTO Teams VALUES( 67, '95', 'VfL Bochum', '波鸿', '波琴');
INSERT INTO Teams VALUES( 68, '160', 'Hamburger SV', '汉堡', '漢堡');
INSERT INTO Teams VALUES( 69, '425', 'Dynamo Dresden', '德累斯顿', '特雷斯登');
INSERT INTO Teams VALUES( 70, '458', 'Greuther Furth', '菲尔特', '格雷特霍夫');
INSERT INTO Teams VALUES( 71, '461', 'Erzgebirge Aue', '奥厄', '奧厄');
INSERT INTO Teams VALUES( 72, '490', 'FC Koln', '科隆', '科隆');
INSERT INTO Teams VALUES( 73, '493', 'MSV Duisburg', '杜伊斯堡', '杜伊斯堡');
INSERT INTO Teams VALUES( 74, '1079', 'Jahn Regensburg', '雷根斯堡', '雷根斯堡');
INSERT INTO Teams VALUES( 75, '1080', 'Darmstadt', '达姆斯塔特', '達斯泰特');
INSERT INTO Teams VALUES( 76, '1085', 'St. Pauli', '圣保利', '聖保利');
INSERT INTO Teams VALUES( 77, '1087', 'Union Berlin', '柏林联合', '柏林聯');
INSERT INTO Teams VALUES( 78, '1117', 'Holstein Kiel', '基尔高士丁', '基爾');
INSERT INTO Teams VALUES( 79, '1720', 'SC Paderborn 07', '柏德博恩', '柏德博恩');
INSERT INTO Teams VALUES( 80, '2760', 'Magdeburg', '马格德堡', '馬德堡');
INSERT INTO Teams VALUES( 81, '2786', 'Ingolstadt', '因戈尔施塔特', '恩高斯達特');
INSERT INTO Teams VALUES( 82, '4449', 'SV Sandhausen', '桑德豪森', '辛特侯遜');
INSERT INTO Teams VALUES( 83, '8371', 'Heidenheimer', '海登海默', '海登海默');
INSERT INTO Teams VALUES( 84, '194', 'Ajaccio', '阿雅克肖', '阿些斯奧');
INSERT INTO Teams VALUES( 85, '202', 'Lens', '朗斯', '朗斯');
INSERT INTO Teams VALUES( 86, '214', 'Metz', '梅斯', '梅斯');
INSERT INTO Teams VALUES( 87, '215', 'AJ Auxerre', '欧塞尔', '歐塞爾');
INSERT INTO Teams VALUES( 88, '267', 'Sochaux', '索肖', '索察');
INSERT INTO Teams VALUES( 89, '301', 'Nancy', '南锡', '南錫');
INSERT INTO Teams VALUES( 90, '306', 'Stade Brestois', '布雷斯特', '比斯特');
INSERT INTO Teams VALUES( 91, '308', 'Chateauroux', '沙托鲁', '沙特魯');
INSERT INTO Teams VALUES( 92, '313', 'Clermont', '克莱蒙', '克萊蒙特');
INSERT INTO Teams VALUES( 93, '325', 'Chamois Niortais', '尼奥特', '尼奧特');
INSERT INTO Teams VALUES( 94, '333', 'Lorient', '洛里昂', '羅連安特');
INSERT INTO Teams VALUES( 95, '335', 'Le Havre', '勒阿弗尔', '勒哈費爾');
INSERT INTO Teams VALUES( 96, '366', 'Troyes', '特鲁瓦', '特魯瓦');
INSERT INTO Teams VALUES( 97, '393', 'Grenoble', '格勒诺布尔', '格勒諾布爾');
INSERT INTO Teams VALUES( 98, '1796', 'Paris FC', 'FC巴黎', '巴黎FC');
INSERT INTO Teams VALUES( 99, '2104', 'Valenciennes', '瓦朗谢纳', '華倫西恩斯');
INSERT INTO Teams VALUES( 100, '2141', 'Ajaccio Gfco', 'GFC阿雅克肖', 'GFCO阿些斯奧');
INSERT INTO Teams VALUES( 101, '5025', 'Orleans US 45', '奥兰斯', '奧爾良');
INSERT INTO Teams VALUES( 102, '12220', 'Red Star FC 93', '红星', '紅星');
INSERT INTO Teams VALUES( 103, '15123', 'Avenir Sportif Beziers', '贝兹尔', '比斯亞斯');
INSERT INTO Teams VALUES( 104, '17', 'Middlesbrough', '米德尔斯堡', '米杜士堡');
INSERT INTO Teams VALUES( 105, '18', 'West Bromwich(WBA)', '西布罗姆维奇', '西布朗');
INSERT INTO Teams VALUES( 106, '20', 'Aston Villa', '阿斯顿维拉', '阿士東維拉');
INSERT INTO Teams VALUES( 107, '21', 'Blackburn Rovers', '布莱克本', '布力般流浪');
INSERT INTO Teams VALUES( 108, '22', 'Bolton Wanderers', '博尔顿', '保頓');
INSERT INTO Teams VALUES( 109, '32', 'Birmingham City', '伯明翰', '伯明翰');
INSERT INTO Teams VALUES( 110, '34', 'Norwich City', '诺维奇', '諾域治');
INSERT INTO Teams VALUES( 111, '47', 'Derby County', '德比郡', '打比郡');
INSERT INTO Teams VALUES( 112, '49', 'Nottingham Forest', '诺丁汉森林', '諾定咸森林');
INSERT INTO Teams VALUES( 113, '50', 'Queens Park Rangers (QPR)', '女王公园巡游者', '昆士柏流浪');
INSERT INTO Teams VALUES( 114, '51', 'Sheffield United', '谢菲尔德联队', '錫菲聯');
INSERT INTO Teams VALUES( 115, '54', 'Rotherham United', '罗瑟汉姆', '洛達咸');
INSERT INTO Teams VALUES( 116, '55', 'Preston North End', '普雷斯顿', '普雷斯頓');
INSERT INTO Teams VALUES( 117, '56', 'Leeds United', '利兹联', '列斯聯');
INSERT INTO Teams VALUES( 118, '58', 'Stoke City', '斯托克城', '史篤城');
INSERT INTO Teams VALUES( 119, '61', 'Wigan Athletic', '维冈竞技', '韋根');
INSERT INTO Teams VALUES( 120, '66', 'Reading', '雷丁', '雷丁');
INSERT INTO Teams VALUES( 121, '68', 'Ipswich Town', '伊普斯维奇', '葉士域治');
INSERT INTO Teams VALUES( 122, '69', 'Millwall', '米尔沃尔', '米禾爾');
INSERT INTO Teams VALUES( 123, '336', 'Sheffield Wednesday', '谢周三', '錫周三');
INSERT INTO Teams VALUES( 124, '365', 'Brentford', '布伦特福德', '賓福特');
INSERT INTO Teams VALUES( 125, '379', 'Bristol City', '布里斯托城', '布里斯托城');
INSERT INTO Teams VALUES( 126, '384', 'Hull City', '赫尔城', '侯城');
INSERT INTO Teams VALUES( 127, '1194', 'Swansea City', '斯旺西', '史雲斯');
INSERT INTO Teams VALUES( 128, '19', 'Arsenal', '阿森纳', '阿仙奴');
INSERT INTO Teams VALUES( 129, '24', 'Chelsea', '切尔西', '車路士');
INSERT INTO Teams VALUES( 130, '25', 'Liverpool', '利物浦', '利物浦');
INSERT INTO Teams VALUES( 131, '26', 'Manchester City', '曼彻斯特城', '曼城');
INSERT INTO Teams VALUES( 132, '27', 'Manchester United', '曼彻斯特联', '曼聯');
INSERT INTO Teams VALUES( 133, '28', 'Newcastle United', '纽卡斯尔联', '紐卡素');
INSERT INTO Teams VALUES( 134, '29', 'Fulham', '富勒姆', '富咸');
INSERT INTO Teams VALUES( 135, '30', 'Southampton', '南安普敦', '修咸頓');
INSERT INTO Teams VALUES( 136, '31', 'Everton', '埃弗顿', '愛華頓');
INSERT INTO Teams VALUES( 137, '33', 'Tottenham Hotspur', '托特纳姆热刺', '熱刺');
INSERT INTO Teams VALUES( 138, '35', 'Crystal Palace', '水晶宫', '水晶宮');
INSERT INTO Teams VALUES( 139, '46', 'Burnley', '伯恩利', '般尼');
INSERT INTO Teams VALUES( 140, '52', 'Wolves', '狼队', '狼隊');
INSERT INTO Teams VALUES( 141, '53', 'Watford', '沃特福德', '屈福特');
INSERT INTO Teams VALUES( 142, '59', 'Leicester City', '莱切斯特城', '李斯特城');
INSERT INTO Teams VALUES( 143, '60', 'Brighton   Hove Albion', '布莱顿', '白禮頓');
INSERT INTO Teams VALUES( 144, '62', 'West Ham United', '西汉姆联', '韋斯咸');
INSERT INTO Teams VALUES( 145, '64', 'Cardiff City', '卡迪夫城', '卡迪夫城');
INSERT INTO Teams VALUES( 146, '344', 'Huddersfield Town', '哈德斯菲尔德', '哈德斯菲爾德');
INSERT INTO Teams VALUES( 147, '348', 'Bournemouth AFC', '伯恩茅斯', '般尼茅夫');
INSERT INTO Teams VALUES( 148, '23', 'Charlton Athletic', '查尔顿', '查爾頓');
INSERT INTO Teams VALUES( 149, '36', 'Portsmouth', '朴茨茅斯', '樸茨茅夫');
INSERT INTO Teams VALUES( 150, '48', 'Gillingham', '吉林汉姆', '基寧咸');
INSERT INTO Teams VALUES( 151, '57', 'Coventry City', '考文垂', '高雲地利');
INSERT INTO Teams VALUES( 152, '63', 'Plymouth Argyle', '普利茅斯', '普利茅夫');
INSERT INTO Teams VALUES( 153, '65', 'Sunderland A.F.C', '桑德兰', '新特蘭');
INSERT INTO Teams VALUES( 154, '338', 'Bradford City', '布拉德福德', '巴拉福特');
INSERT INTO Teams VALUES( 155, '339', 'Walsall', '沃尔索尔', '華素爾');
INSERT INTO Teams VALUES( 156, '341', 'Doncaster Rovers', '唐卡斯特', '唐卡士打');
INSERT INTO Teams VALUES( 157, '353', 'Peterborough United', '彼得堡联', '彼德堡');
INSERT INTO Teams VALUES( 158, '372', 'Luton Town', '卢顿', '盧頓');
INSERT INTO Teams VALUES( 159, '377', 'Blackpool', '布莱克浦', '黑池');
INSERT INTO Teams VALUES( 160, '378', 'Barnsley', '巴恩斯利', '班士利');
INSERT INTO Teams VALUES( 161, '1179', 'Accrington Stanley', '阿克灵顿', '艾寧頓');
INSERT INTO Teams VALUES( 162, '1190', 'Bristol Rovers', '布里斯托流浪', '布里斯托流浪');
INSERT INTO Teams VALUES( 163, '1192', 'Wycombe Wanderers', '韦康比流浪者', '韋甘比');
INSERT INTO Teams VALUES( 164, '1196', 'Shrewsbury Town', '谢斯伯利', '梳士貝利');
INSERT INTO Teams VALUES( 165, '1198', 'Scunthorpe United', '斯坎索普', '斯肯索普');
INSERT INTO Teams VALUES( 166, '1201', 'Oxford United', '牛津联队', '牛津聯');
INSERT INTO Teams VALUES( 167, '1203', 'Rochdale', '罗奇代尔', '羅奇代爾');
INSERT INTO Teams VALUES( 168, '1207', 'Southend United', '南安联', '修安聯');
INSERT INTO Teams VALUES( 169, '1381', 'Burton Albion', '伯顿', '伯頓');
INSERT INTO Teams VALUES( 170, '3545', 'AFC Wimbledon', 'AFC温布尔登', 'AFC溫布頓');
INSERT INTO Teams VALUES( 171, '3902', 'Fleetwood Town', '弗利特伍德', '費列活特');
INSERT INTO Teams VALUES( 172, '67', 'Crewe Alexandra', '克鲁', '克魯');
INSERT INTO Teams VALUES( 173, '334', 'Milton Keynes Dons', '米尔顿凯恩斯', '米爾頓凱恩斯');
INSERT INTO Teams VALUES( 174, '346', 'Port Vale', '维尔港', '維爾港');
INSERT INTO Teams VALUES( 175, '357', 'Oldham Athletic', '奥德汉姆', '奧咸');
INSERT INTO Teams VALUES( 176, '361', 'Swindon Town', '斯文登', '史雲頓');
INSERT INTO Teams VALUES( 177, '363', 'Tranmere Rovers', '特兰米尔', '燦美爾');
INSERT INTO Teams VALUES( 178, '376', 'Colchester United', '科切斯特联', '高車士打');
INSERT INTO Teams VALUES( 179, '1181', 'Carlisle United', '卡利斯尔联', '卡素爾');
INSERT INTO Teams VALUES( 180, '1186', 'Crawley Town', '克劳利', '卡維尼');
INSERT INTO Teams VALUES( 181, '1187', 'Cambridge United', '剑桥联', '劍橋聯');
INSERT INTO Teams VALUES( 182, '1188', 'Lincoln City', '林肯城', '林肯城');
INSERT INTO Teams VALUES( 183, '1193', 'Grimsby Town', '格林斯比', '甘士比');
INSERT INTO Teams VALUES( 184, '1199', 'Mansfield Town', '曼斯菲特', '曼斯菲特');
INSERT INTO Teams VALUES( 185, '1200', 'Bury', '伯利', '貝利');
INSERT INTO Teams VALUES( 186, '1202', 'Cheltenham Town', '切尔滕汉姆', '車頓咸');
INSERT INTO Teams VALUES( 187, '1204', 'Macclesfield Town', '马科斯菲尔德', '馬格斯菲特');
INSERT INTO Teams VALUES( 188, '1206', 'Notts County', '诺茨郡', '諾士郡');
INSERT INTO Teams VALUES( 189, '1208', 'Northampton Town', '北安普敦', '諾咸頓');
INSERT INTO Teams VALUES( 190, '1211', 'Yeovil Town', '耶奥维尔', '伊奧華');
INSERT INTO Teams VALUES( 191, '1356', 'Exeter City', '埃克塞特城', '埃克塞特');
INSERT INTO Teams VALUES( 192, '1380', 'Morecambe', '莫雷坎比', '摩爾甘比');
INSERT INTO Teams VALUES( 193, '1386', 'Stevenage Borough', '斯蒂文尼奇', '史提芬納治');
INSERT INTO Teams VALUES( 194, '1388', 'Forest Green Rovers', '格兰森林流浪', '格蘭森林流浪');
INSERT INTO Teams VALUES( 195, '3427', 'Newport County', '纽波特', '新港');
INSERT INTO Teams VALUES( 196, '82', 'Real Madrid', '皇家马德里', '皇家馬德里');
INSERT INTO Teams VALUES( 197, '84', 'FC Barcelona', '巴塞罗那', '巴塞隆拿');
INSERT INTO Teams VALUES( 198, '86', 'Sevilla', '塞维利亚', '西維爾');
INSERT INTO Teams VALUES( 199, '91', 'Valencia', '巴伦西亚', '華倫西亞');
INSERT INTO Teams VALUES( 200, '92', 'Athletic Bilbao', '毕尔巴鄂竞技', '畢爾包');
INSERT INTO Teams VALUES( 201, '96', 'Real Betis', '皇家贝蒂斯', '貝迪斯');
INSERT INTO Teams VALUES( 202, '98', 'Getafe', '赫塔菲', '加泰');
INSERT INTO Teams VALUES( 203, '100', 'RCD Espanyol', '西班牙人', '愛斯賓奴');
INSERT INTO Teams VALUES( 204, '103', 'Levante', '莱万特', '利雲特');
INSERT INTO Teams VALUES( 205, '106', 'Real Sociedad', '皇家社会', '皇家蘇斯達');
INSERT INTO Teams VALUES( 206, '107', 'Villarreal', '比利亚雷亚尔', '維拉利爾');
INSERT INTO Teams VALUES( 207, '109', 'Atletico Madrid', '马德里竞技', '馬德里體育會');
INSERT INTO Teams VALUES( 208, '114', 'Celta Vigo', '塞尔塔', '切爾達');
INSERT INTO Teams VALUES( 209, '123', 'Real Valladolid', '瓦拉多利德', '華拉度列');
INSERT INTO Teams VALUES( 210, '131', 'Eibar', '埃瓦尔', '伊巴');
INSERT INTO Teams VALUES( 211, '137', 'Alaves', '阿拉维斯', '艾拉維斯');
INSERT INTO Teams VALUES( 212, '982', 'Girona', '赫罗纳', '傑羅納');
INSERT INTO Teams VALUES( 213, '992', 'Leganes', '莱加内斯', '雷加利斯');
INSERT INTO Teams VALUES( 214, '994', 'Rayo Vallecano', '巴列卡诺', '華歷簡奴');
INSERT INTO Teams VALUES( 215, '3225', 'SD Huesca', '韦斯卡', '侯爾斯卡');
INSERT INTO Teams VALUES( 216, '150', 'AC Milan', 'AC米兰', 'AC米蘭');
INSERT INTO Teams VALUES( 217, '152', 'Inter Milan', '国际米兰', '國際米蘭');
INSERT INTO Teams VALUES( 218, '154', 'Atalanta', '亚特兰大', '阿特蘭大');
INSERT INTO Teams VALUES( 219, '166', 'Juventus', '尤文图斯', '祖雲達斯');
INSERT INTO Teams VALUES( 220, '174', 'AS Roma', '罗马', '羅馬');
INSERT INTO Teams VALUES( 221, '176', 'Fiorentina', '佛罗伦萨', '費倫天拿');
INSERT INTO Teams VALUES( 222, '179', 'Sampdoria', '桑普多利亚', '森多利亞');
INSERT INTO Teams VALUES( 223, '182', 'Lazio', '拉齐奥', '拉素');
INSERT INTO Teams VALUES( 224, '183', 'Cagliari', '卡利亚里', '卡利亞里');
INSERT INTO Teams VALUES( 225, '185', 'Bologna', '博洛尼亚', '博洛尼亞');
INSERT INTO Teams VALUES( 226, '187', 'Udinese', '乌迪内斯', '烏甸尼斯');
INSERT INTO Teams VALUES( 227, '189', 'Parma', '帕尔马', '帕爾馬');
INSERT INTO Teams VALUES( 228, '195', 'Chievo', '切沃', '切禾');
INSERT INTO Teams VALUES( 229, '523', 'Empoli', '恩波利', '恩波里');
INSERT INTO Teams VALUES( 230, '552', 'Genoa', '热那亚', '熱拿亞');
INSERT INTO Teams VALUES( 231, '558', 'Torino', '都灵', '拖連奴');
INSERT INTO Teams VALUES( 232, '1359', 'Frosinone', '弗洛西诺尼', '費辛隆尼');
INSERT INTO Teams VALUES( 233, '1408', 'Spal', '史帕尔', '史帕爾');
INSERT INTO Teams VALUES( 234, '1419', 'Napoli', '那不勒斯', '拿玻里');
INSERT INTO Teams VALUES( 235, '2960', 'Sassuolo', '森索罗', '莎索羅');
INSERT INTO Teams VALUES( 236, '88', 'Bayern Munchen', '拜仁慕尼黑', '拜仁慕尼黑');
INSERT INTO Teams VALUES( 237, '99', 'Borussia Dortmund', '多特蒙德', '多蒙特');
INSERT INTO Teams VALUES( 238, '128', 'Borussia Monchengladbach', '门兴格拉德巴赫', '慕遜加柏');
INSERT INTO Teams VALUES( 239, '132', 'Werder Bremen', '云达不莱梅', '雲達不萊梅');
INSERT INTO Teams VALUES( 240, '136', 'Nurnberg', '纽伦堡', '紐倫堡');
INSERT INTO Teams VALUES( 241, '139', 'Hertha Berlin', '柏林赫塔', '哈化柏林');
INSERT INTO Teams VALUES( 242, '149', 'VfL Wolfsburg', '沃尔夫斯堡', '沃爾夫斯堡');
INSERT INTO Teams VALUES( 243, '151', 'Schalke 04', '沙尔克04', '史浩克零四');
INSERT INTO Teams VALUES( 244, '155', 'VfB Stuttgart', '斯图加特', '史特加');
INSERT INTO Teams VALUES( 245, '162', 'FSV Mainz 05', '美因茨', '緬恩斯');
INSERT INTO Teams VALUES( 246, '165', 'Bayer Leverkusen', '勒沃库森', '利華古遜');
INSERT INTO Teams VALUES( 247, '169', 'Hannover 96', '汉诺威96', '漢諾威');
INSERT INTO Teams VALUES( 248, '172', 'SC Freiburg', '弗赖堡', '費雷堡');
INSERT INTO Teams VALUES( 249, '423', 'Eintracht Frankfurt', '法兰克福', '法蘭克福');
INSERT INTO Teams VALUES( 250, '1078', 'TSG Hoffenheim', '霍芬海姆', '賀芬咸');
INSERT INTO Teams VALUES( 251, '1135', 'Augsburg', '奥格斯堡', '奧格斯堡');
INSERT INTO Teams VALUES( 252, '1344', 'Fortuna Dusseldorf', '杜塞尔多夫', '杜斯多夫');
INSERT INTO Teams VALUES( 253, '13201', 'RB Leipzig', 'RB莱比锡', 'RB萊比錫');
INSERT INTO Teams VALUES( 254, '197', 'Monaco', '摩纳哥', '摩納哥');
INSERT INTO Teams VALUES( 255, '205', 'Lyon', '里昂', '里昂');
INSERT INTO Teams VALUES( 256, '208', 'Bordeaux', '波尔多', '波爾多');
INSERT INTO Teams VALUES( 257, '211', 'Marseille', '马赛', '馬賽');
INSERT INTO Teams VALUES( 258, '216', 'Toulouse', '图卢兹', '圖魯茲');
INSERT INTO Teams VALUES( 259, '251', 'Rennes', '雷恩', '雷恩');
INSERT INTO Teams VALUES( 260, '255', 'Saint Etienne', '圣埃蒂安', '聖伊天');
INSERT INTO Teams VALUES( 261, '257', 'Caen', '卡昂', '卡昂');
INSERT INTO Teams VALUES( 262, '259', 'Nice', '尼斯', '奈斯');
INSERT INTO Teams VALUES( 263, '260', 'Strasbourg', '斯特拉斯堡', '史特拉斯堡');
INSERT INTO Teams VALUES( 264, '263', 'Nantes', '南特', '南特');
INSERT INTO Teams VALUES( 265, '266', 'Lille', '里尔', '利爾');
INSERT INTO Teams VALUES( 266, '271', 'Paris Saint Germain (PSG)', '巴黎圣日尔曼', '巴黎聖日門');
INSERT INTO Teams VALUES( 267, '304', 'Angers', '安格斯', '昂熱');
INSERT INTO Teams VALUES( 268, '320', 'Dijon', '第戎', '迪安');
INSERT INTO Teams VALUES( 269, '351', 'Montpellier', '蒙彼利埃', '蒙彼利埃');
INSERT INTO Teams VALUES( 270, '362', 'Guingamp', '甘冈', '吉英坎');
INSERT INTO Teams VALUES( 271, '382', 'Amiens', '亚眠', '阿美恩斯');
INSERT INTO Teams VALUES( 272, '1744', 'Nimes', '尼姆', '尼姆');
INSERT INTO Teams VALUES( 273, '4957', 'Reims', '兰斯', '蘭斯');
INSERT INTO Teams VALUES( 274, '158', 'Lecce', '莱切', '萊切');
INSERT INTO Teams VALUES( 275, '163', 'Brescia', '布雷西亚', '布雷西亞');
INSERT INTO Teams VALUES( 276, '168', 'Palermo', '巴勒莫', '巴勒莫');
INSERT INTO Teams VALUES( 277, '192', 'Livorno', '利沃诺', '利禾奴');
INSERT INTO Teams VALUES( 278, '527', 'Ascoli', '阿斯科利', '阿斯科利');
INSERT INTO Teams VALUES( 279, '553', 'Perugia', '佩鲁贾', '佩魯賈');
INSERT INTO Teams VALUES( 280, '554', 'Crotone', '克罗托内', '克羅托內');
INSERT INTO Teams VALUES( 281, '557', 'Venezia', '威尼斯', '威尼斯');
INSERT INTO Teams VALUES( 282, '559', 'Verona', '维罗纳', '維羅納');
INSERT INTO Teams VALUES( 283, '560', 'Pescara', '佩斯卡拉', '比斯卡拉');
INSERT INTO Teams VALUES( 284, '562', 'Salernitana', '萨勒尼塔纳', '沙蘭力坦拿');
INSERT INTO Teams VALUES( 285, '1390', 'Spezia', '斯佩齐亚', '史柏斯亞');
INSERT INTO Teams VALUES( 286, '1399', 'Cremonese', '克雷莫纳', '克雷莫納');
INSERT INTO Teams VALUES( 287, '1404', 'Padova', '帕多瓦', '帕多瓦');
INSERT INTO Teams VALUES( 288, '1407', 'Cittadella', '希塔德拉', '薛達迪拿');
INSERT INTO Teams VALUES( 289, '1409', 'Foggia', '福贾', '霍治亞');
INSERT INTO Teams VALUES( 290, '1420', 'Benevento', '贝内文托', '賓尼雲圖');
INSERT INTO Teams VALUES( 291, '9206', 'Cosenza Calcio 1914', '科森扎', '科森察');
INSERT INTO Teams VALUES( 292, '15060', 'Carpi', '卡皮', '卡爾比');
INSERT INTO Teams VALUES( 293, '87', 'Numancia', '努曼西亚', '紐文西亞');
INSERT INTO Teams VALUES( 294, '93', 'Deportivo La Coruna', '拉科鲁尼亚', '拉科魯尼亞');
INSERT INTO Teams VALUES( 295, '94', 'Osasuna', '奥萨苏纳', '奧沙辛拿');
INSERT INTO Teams VALUES( 296, '101', 'Mallorca', '马洛卡', '馬略卡');
INSERT INTO Teams VALUES( 297, '102', 'Malaga', '马拉加', '馬拉加');
INSERT INTO Teams VALUES( 298, '110', 'Albacete', '阿尔巴切特', '阿爾巴塞特');
INSERT INTO Teams VALUES( 299, '111', 'Real Zaragoza', '萨拉戈萨', '薩拉戈薩');
INSERT INTO Teams VALUES( 300, '113', 'Sporting Gijon', '希洪竞技', '希杭');
INSERT INTO Teams VALUES( 301, '119', 'Gimnastic Tarragona', '塔拉戈纳', '塔拉哥納');
INSERT INTO Teams VALUES( 302, '121', 'Granada CF', '格拉那达', '格蘭納達');
INSERT INTO Teams VALUES( 303, '126', 'Elche', '艾尔切', '艾爾切');
INSERT INTO Teams VALUES( 304, '138', 'Tenerife', '特内里费', '特内里費');
INSERT INTO Teams VALUES( 305, '141', 'Almeria', '阿尔梅里亚', '艾美利亞');
INSERT INTO Teams VALUES( 306, '143', 'Cadiz', '卡迪斯', '卡迪斯');
INSERT INTO Teams VALUES( 307, '146', 'Cordoba', '科尔多瓦', '科爾多瓦');
INSERT INTO Teams VALUES( 308, '991', 'Las Palmas', '拉斯帕尔马斯', '拉斯彭馬斯');
INSERT INTO Teams VALUES( 309, '3214', 'AD Alcorcon', '艾科坎', '艾高干');
INSERT INTO Teams VALUES( 310, '3235', 'Extremadura', '艾斯马度华', '艾斯馬度華');
INSERT INTO Teams VALUES( 311, '4657', 'CD Lugo', '卢高', '盧高');
INSERT INTO Teams VALUES( 312, '4732', 'Real Oviedo', '奥维多', '奧維多');
INSERT INTO Teams VALUES( 313, '17009', 'CF Reus Deportiu', '雷乌斯', '雷烏斯');
INSERT INTO Teams VALUES( 314, '19006', 'CF Rayo Majadahonda', '瑞欧马加达宏达', '瑞歐馬加達宏達');
INSERT INTO Teams VALUES( 315, '440', 'Vitoria Setubal', '塞图巴尔', '塞圖巴爾');
INSERT INTO Teams VALUES( 316, '452', 'Maritimo', '马里迪莫', '馬里迪莫');
INSERT INTO Teams VALUES( 317, '457', 'Boavista FC', '博阿维斯塔', '博維斯塔');
INSERT INTO Teams VALUES( 318, '459', 'Sporting Braga', '布拉加', '布拉加');
INSERT INTO Teams VALUES( 319, '463', 'Benfica', '本菲卡', '賓菲加');
INSERT INTO Teams VALUES( 320, '466', 'Sporting Lisbon', '里斯本竞技', '士砵亭');
INSERT INTO Teams VALUES( 321, '468', 'FC Porto', '波尔图', '波圖');
INSERT INTO Teams VALUES( 322, '476', 'Rio Ave', '里奥阿维', '里奧阿維');
INSERT INTO Teams VALUES( 323, '924', 'Moreirense', '摩里伦斯', '摩里倫斯');
INSERT INTO Teams VALUES( 324, '926', 'Belenenses', '比兰尼塞斯', '比蘭倫斯');
INSERT INTO Teams VALUES( 325, '927', 'Vitoria Guimaraes', '吉马雷斯', '甘馬雷斯');
INSERT INTO Teams VALUES( 326, '951', 'Nacional da Madeira', '葡萄牙国民', '國民隊');
INSERT INTO Teams VALUES( 327, '999', 'GD Chaves', '查维斯', '沙維斯');
INSERT INTO Teams VALUES( 328, '1000', 'Aves', '艾维斯', '艾維斯');
INSERT INTO Teams VALUES( 329, '1002', 'Santa Clara', '辛达卡拉', '辛達卡拉');
INSERT INTO Teams VALUES( 330, '1554', 'Portimonense', '朴迪莫伦斯', '樸迪莫倫斯');
INSERT INTO Teams VALUES( 331, '1555', 'Feirense', '费伦斯', '費倫斯');
INSERT INTO Teams VALUES( 332, '19599', 'CD Tondela', '唐迪拉', '唐迪拉');
INSERT INTO Teams VALUES( 333, '443', 'Academica Coimbra', '科英布拉大学', '科英布拉大學');
INSERT INTO Teams VALUES( 334, '483', 'Penafiel', '佩纳菲尔', '彭拿費爾');
INSERT INTO Teams VALUES( 335, '486', 'Estoril', '埃斯托里尔', '伊斯托里爾');
INSERT INTO Teams VALUES( 336, '1006', 'Pacos de Ferreira', '费雷拉', '費利拿');
INSERT INTO Teams VALUES( 337, '1047', 'Leixoes', '雷克斯欧斯', '歷索斯');
INSERT INTO Teams VALUES( 338, '1552', 'Varzim', '华森', '華森');
INSERT INTO Teams VALUES( 339, '1685', 'Oliveirense', '奥利维伦斯', '奧利維倫斯');
INSERT INTO Teams VALUES( 340, '1805', 'Viseu', '维塞乌', '維塞烏');
INSERT INTO Teams VALUES( 341, '2797', 'SC Covilha', '科维良', '高維拿');
INSERT INTO Teams VALUES( 342, '4970', 'FC Famalicao', '法马利卡奥', '法馬利卡奧');
INSERT INTO Teams VALUES( 343, '4979', 'CD Mafra', '马夫拉', '馬弗拉');
INSERT INTO Teams VALUES( 344, '9046', 'FC Arouca', '艾路卡', '阿洛卡');
INSERT INTO Teams VALUES( 345, '11499', 'SC Farense', '法伦斯', '法倫斯');
INSERT INTO Teams VALUES( 346, '19786', 'SL Benfica B', '宾菲加B队', '賓菲加B隊');
INSERT INTO Teams VALUES( 347, '19787', 'Vitoria Guimaraes B', '甘马雷斯B队', '甘馬雷斯B隊');
INSERT INTO Teams VALUES( 348, '19869', 'Sporting Braga II', '布拉加B队', '布拉加B隊');
INSERT INTO Teams VALUES( 349, '20158', 'Porto B', '波尔图B队', '波圖B隊');
INSERT INTO Teams VALUES( 350, '22230', 'Cova Piedade', '科瓦皮耶达迪', '科瓦皮耶達迪');
INSERT INTO Teams VALUES( 351, '70', 'Celtic FC', '凯尔特人', '些路迪');
INSERT INTO Teams VALUES( 352, '71', 'Dundee', '邓迪FC', '登地');
INSERT INTO Teams VALUES( 353, '73', 'Aberdeen', '阿伯丁', '鴨巴甸');
INSERT INTO Teams VALUES( 354, '75', 'Motherwell', '马瑟韦尔', '馬瑟韋爾');
INSERT INTO Teams VALUES( 355, '76', 'Heart of Midlothian', '哈茨', '赫斯');
INSERT INTO Teams VALUES( 356, '77', 'Glasgow Rangers', '格拉斯哥流浪者', '格拉斯哥流浪');
INSERT INTO Teams VALUES( 357, '79', 'Hibernian', '希伯尼安', '喜百年');
INSERT INTO Teams VALUES( 358, '80', 'Livingston', '利云斯顿', '利雲斯頓');
INSERT INTO Teams VALUES( 359, '81', 'Kilmarnock', '基马诺克', '基馬諾克');
INSERT INTO Teams VALUES( 360, '1460', 'Hamilton Academical', '哈密尔顿', '咸美頓');
INSERT INTO Teams VALUES( 361, '1463', 'Saint Mirren', '圣米伦', '聖美倫');
INSERT INTO Teams VALUES( 362, '1485', 'Saint Johnstone', '圣约翰斯通', '聖莊士東');
INSERT INTO Teams VALUES( 363, '72', 'Dundee United', '邓迪联队', '登地聯');
INSERT INTO Teams VALUES( 364, '74', 'Dunfermline Athletic', '邓弗姆林', '鄧弗姆林');
INSERT INTO Teams VALUES( 365, '78', 'Inverness', '因弗内斯', '恩華利斯');
INSERT INTO Teams VALUES( 366, '1366', 'Ross County', '罗斯郡', '羅斯郡');
INSERT INTO Teams VALUES( 367, '1367', 'Falkirk', '法基克', '福克爾克');
INSERT INTO Teams VALUES( 368, '1461', 'Queen of South', '南部女王', '南部皇後');
INSERT INTO Teams VALUES( 369, '1462', 'Partick Thistle', '帕尔蒂克', '巴特里');
INSERT INTO Teams VALUES( 370, '1467', 'Greenock Morton', '摩顿', '摩頓');
INSERT INTO Teams VALUES( 371, '1471', 'Alloa Athletic', '艾洛亚', '阿洛厄');
INSERT INTO Teams VALUES( 372, '17137', 'Ayr United', '艾尔联', '艾爾');
INSERT INTO Teams VALUES( 373, '225', 'Willem II', '威廉二世', '威廉二世');
INSERT INTO Teams VALUES( 374, '232', 'NAC Breda', '布雷达', '比達');
INSERT INTO Teams VALUES( 375, '234', 'AZ Alkmaar', '艾克马亚', '艾克馬亞');
INSERT INTO Teams VALUES( 376, '235', 'SC Heerenveen', '海伦芬', '海倫維恩');
INSERT INTO Teams VALUES( 377, '236', 'Groningen', '格罗宁根', '高寧根');
INSERT INTO Teams VALUES( 378, '237', 'FC Utrecht', '乌德勒支', '烏德勒支');
INSERT INTO Teams VALUES( 379, '243', 'De Graafschap', '格拉夫夏普', '迪加史卓普');
INSERT INTO Teams VALUES( 380, '246', 'Vitesse Arnhem', '维迪斯', '維迪斯');
INSERT INTO Teams VALUES( 381, '252', 'Feyenoord', '费耶诺德', '飛燕諾');
INSERT INTO Teams VALUES( 382, '253', 'AFC Ajax', '阿贾克斯', '阿積士');
INSERT INTO Teams VALUES( 383, '254', 'PSV Eindhoven', '埃因霍温', 'PSV燕豪芬');
INSERT INTO Teams VALUES( 384, '256', 'ADO Den Haag', '海牙', '海牙');
INSERT INTO Teams VALUES( 385, '270', 'Excelsior SBV', 'SBV精英', 'SBV精英隊');
INSERT INTO Teams VALUES( 386, '274', 'Fortuna Sittard', '福图纳锡塔德', '幸運薛達');
INSERT INTO Teams VALUES( 387, '277', 'VVV Venlo', '芬洛', '芬洛');
INSERT INTO Teams VALUES( 388, '278', 'Heracles Almelo', '赫拉克莱斯', '荷華高斯');
INSERT INTO Teams VALUES( 389, '414', 'PEC Zwolle', '泽沃勒', '施禾尼');
INSERT INTO Teams VALUES( 390, '1093', 'Emmen', '埃蒙', '安曼');
INSERT INTO Teams VALUES( 391, '181', 'Nagoya Grampus', '名古屋鲸八', '名古屋八鯨');
INSERT INTO Teams VALUES( 392, '188', 'Urawa Red Diamonds', '浦和红钻', '浦和紅鑽');
INSERT INTO Teams VALUES( 393, '190', 'Kashima Antlers', '鹿岛鹿角', '鹿島鹿角');
INSERT INTO Teams VALUES( 394, '193', 'Cerezo Osaka', '大阪樱花', '大阪櫻花');
INSERT INTO Teams VALUES( 395, '196', 'Yokohama Marinos', '横滨水手', '橫濱水手');
INSERT INTO Teams VALUES( 396, '198', 'Jubilo Iwata', '磐田喜悦', '磐田山葉');
INSERT INTO Teams VALUES( 397, '201', 'FC Tokyo', 'FC东京', 'FC東京');
INSERT INTO Teams VALUES( 398, '203', 'Vissel Kobe', '神户胜利船', '神戶勝利船');
INSERT INTO Teams VALUES( 399, '204', 'Shimizu S-Pulse', '清水鼓动', '清水心跳');
INSERT INTO Teams VALUES( 400, '206', 'Hiroshima Sanfrecce', '广岛三箭', '廣島三箭');
INSERT INTO Teams VALUES( 401, '207', 'Gamba Osaka', '大阪钢巴', '大阪飛腳');
INSERT INTO Teams VALUES( 402, '209', 'Kashiwa Reysol', '柏太阳神', '柏雷素爾');
INSERT INTO Teams VALUES( 403, '1612', 'Shonan Bellmare', '湘南海洋', '湘南比馬');
INSERT INTO Teams VALUES( 404, '1989', 'Kawasaki Frontale', '川崎前锋', '川崎前鋒');
INSERT INTO Teams VALUES( 405, '3164', 'Sagan Tosu', '鸟栖沙岩', '鳥栖沙岩');
INSERT INTO Teams VALUES( 406, '3193', 'Vegalta Sendai', '仙台维加泰', '仙台維加泰');
INSERT INTO Teams VALUES( 407, '3195', 'Consadole Sapporo', '札幌冈萨多', '札幌岡薩多');
INSERT INTO Teams VALUES( 408, '10031', 'V-Varen Nagasaki', '长崎成功丸', '長崎成功丸');
INSERT INTO Teams VALUES( 409, '39', 'Shanghai Shenhua', '上海绿地申花', '上海绿地申花');
INSERT INTO Teams VALUES( 410, '40', 'Shandong Luneng', '山东鲁能泰山', '山東魯能泰山');
INSERT INTO Teams VALUES( 411, '43', 'Beijing Guoan', '北京中赫国安', '北京中赫國安');
INSERT INTO Teams VALUES( 412, '83', 'Chongqing SWM Motors', '重庆斯威', '重慶斯威');
INSERT INTO Teams VALUES( 413, '89', 'Tianjin Teda', '天津泰达亿利', '天津泰達');
INSERT INTO Teams VALUES( 414, '528', 'Changchun Yatai', '长春亚泰', '長春亞泰');
INSERT INTO Teams VALUES( 415, '535', 'Guangzhou Evergrande Taobao FC', '广州恒大淘宝', '廣州恆大淘寶');
INSERT INTO Teams VALUES( 416, '541', 'Henan Jianye', '河南建业', '河南建業');
INSERT INTO Teams VALUES( 417, '543', 'Jiangsu Suning FC', '江苏苏宁', '江蘇蘇寧');
INSERT INTO Teams VALUES( 418, '3969', 'Beijing Renhe', '北京人和', '北京人和');
INSERT INTO Teams VALUES( 419, '7642', 'Shanghai East Asia FC', '上海上港', '上海上港');
INSERT INTO Teams VALUES( 420, '8685', 'Tianjin QuanJian', '天津权健', '天津權健');
INSERT INTO Teams VALUES( 421, '8686', 'Guizhou Hengfeng Zhicheng', '贵州恒丰智诚', '貴州恒丰智誠');
INSERT INTO Teams VALUES( 422, '13969', 'Dalian Aerbin', '大连一方', '大連一方');
INSERT INTO Teams VALUES( 423, '16668', 'Guangzhou Fuli FC', '广州富力', '廣州富力');
INSERT INTO Teams VALUES( 424, '16961', 'Hebei HX Xingfu', '河北华夏幸福', '河北華夏幸福');
INSERT INTO Teams VALUES( 425, '37', 'Shenzhen JiaZhaoye', '深圳佳兆业', '深圳佳兆業');
INSERT INTO Teams VALUES( 426, '41', 'Liaoning FC', '辽宁沈阳开新', '遼寧宏運');
INSERT INTO Teams VALUES( 427, '542', 'Zhejiang Greentown', '浙江绿城', '浙江綠城');
INSERT INTO Teams VALUES( 428, '1998', 'Yanbian', '延边富德', '延邊富德');
INSERT INTO Teams VALUES( 429, '4050', 'Shanghai Shenxin', '上海申鑫', '上海申鑫');
INSERT INTO Teams VALUES( 430, '10449', 'Beijing BeiKong', '北京北控燕京', '北京北控');
INSERT INTO Teams VALUES( 431, '16667', 'Wuhan ZALL', '武汉卓尔', '武漢卓爾');
INSERT INTO Teams VALUES( 432, '16952', 'Zhejiang Yiteng FC', '浙江毅腾轻纺城', '浙江毅騰輕紡城');
INSERT INTO Teams VALUES( 433, '16967', 'Shijiazhuang YongChang FC', '石家庄永昌', '石家莊永昌');
INSERT INTO Teams VALUES( 434, '19342', 'Xinjiang Tianshan Leopard', '新疆体彩', '新疆體彩');
INSERT INTO Teams VALUES( 435, '21227', 'Meizhou Hakka', '梅州客家', '梅州客家');
INSERT INTO Teams VALUES( 436, '21408', 'Qingdao Huanghai F.C.', '青岛黄海制药', '青島黃海制藥');
INSERT INTO Teams VALUES( 437, '22873', 'Dalian Chaoyue', '大连超越', '大連超越');
INSERT INTO Teams VALUES( 438, '22911', 'Meizhou Meixian Techand', '梅县铁汉生态', '梅縣鐵漢');
INSERT INTO Teams VALUES( 439, '22916', 'Inner Mongolia Zhongyou', '内蒙古中优', '內蒙古中優');
INSERT INTO Teams VALUES( 440, '26533', 'Heilongjiang Lava Spring', '黑龙江火山鸣泉', '黑龍江火山鳴泉');
INSERT INTO Teams VALUES( 441, '337', 'Santos', '桑托斯', '山度士');
INSERT INTO Teams VALUES( 442, '343', 'Atletico Mineiro', '米内罗竞技', '明尼路');
INSERT INTO Teams VALUES( 443, '347', 'Atletico Paranaense', '巴拉纳竞技', '巴拉納體育會');
INSERT INTO Teams VALUES( 444, '349', 'Corinthians Paulista (SP)', '科林蒂安', '哥連泰斯');
INSERT INTO Teams VALUES( 445, '354', 'Cruzeiro (MG)', '克鲁塞罗', '高士路');
INSERT INTO Teams VALUES( 446, '356', 'Flamengo', '弗拉门戈', '法林明高');
INSERT INTO Teams VALUES( 447, '364', 'Gremio (RS)', '格雷米奥', '甘美奧');
INSERT INTO Teams VALUES( 448, '369', 'Internacional RS', '巴西国际', '國際體育會');
INSERT INTO Teams VALUES( 449, '453', 'Sao Paulo', '圣保罗', '聖保羅');
INSERT INTO Teams VALUES( 450, '456', 'Vasco da Gama', '瓦斯科达伽马', '華斯高');
INSERT INTO Teams VALUES( 451, '462', 'Vitoria BA', '维多利亚', '維多利亞');
INSERT INTO Teams VALUES( 452, '465', 'Palmeiras', '帕尔梅拉斯', '彭美拉斯');
INSERT INTO Teams VALUES( 453, '467', 'Botafogo RJ', '博塔弗戈', '保地花高');
INSERT INTO Teams VALUES( 454, '469', 'Fluminense RJ', '弗鲁米嫩塞', '富明尼斯');
INSERT INTO Teams VALUES( 455, '1979', 'Bahia BA', '巴伊亚', '巴希亞');
INSERT INTO Teams VALUES( 456, '2108', 'Ceara', '塞阿拉', '施亞拉');
INSERT INTO Teams VALUES( 457, '2449', 'Parana PR', '巴拉纳', '巴拉納');
INSERT INTO Teams VALUES( 458, '4176', 'Sport Club Recife PE', '累西腓体育', '利斯菲體育會');
INSERT INTO Teams VALUES( 459, '7344', 'Chapecoense SC', '沙佩科恩斯', '查比高恩斯');
INSERT INTO Teams VALUES( 460, '13219', 'America MG', '米内罗美洲', '阿美利加明尼路');
INSERT INTO Teams VALUES( 461, '350', 'Coritiba PR', '科里蒂巴', '哥列迪巴');
INSERT INTO Teams VALUES( 462, '352', 'Criciuma', '克里丘马', '基斯奧馬');
INSERT INTO Teams VALUES( 463, '355', 'Figueirense', '费古埃伦斯', '費古倫斯');
INSERT INTO Teams VALUES( 464, '360', 'Goias', '戈伊亚斯', '戈亞斯');
INSERT INTO Teams VALUES( 465, '367', 'Guarani SP', '巴西瓜拉尼', '古蘭尼');
INSERT INTO Teams VALUES( 466, '371', 'Juventude', '尤文图德', '尤文都德');
INSERT INTO Teams VALUES( 467, '375', 'SC Paysandu Para', '帕桑度', '彼辛度');
INSERT INTO Teams VALUES( 468, '381', 'Ponte Preta', '庞特普雷塔', '邦迪比達');
INSERT INTO Teams VALUES( 469, '1942', 'Londrina PR', '隆迪那', '隆德里納');
INSERT INTO Teams VALUES( 470, '1947', 'Sampaio Correa', '森柏欧', '森柏歐');
INSERT INTO Teams VALUES( 471, '1972', 'Vila Nova', '维拉诺瓦', '維拉諾瓦');
INSERT INTO Teams VALUES( 472, '2001', 'Fortaleza', '福塔雷萨', '科泰尼沙');
INSERT INTO Teams VALUES( 473, '3824', 'Sao Bento', '萨本托', '聖本托');
INSERT INTO Teams VALUES( 474, '3954', 'CRB AL', 'CR巴西', '瑞加塔斯');
INSERT INTO Teams VALUES( 475, '4175', 'Avai FC SC', '奥瓦', '艾華爾');
INSERT INTO Teams VALUES( 476, '5156', 'Atletico Clube Goianiense', '戈亚尼亚竞技', '戈亞尼恩斯');
INSERT INTO Teams VALUES( 477, '7338', 'Boa Esporte Clube', '伊图乌塔', '博阿');
INSERT INTO Teams VALUES( 478, '9673', 'Oeste', '欧斯特', '歐斯特');
INSERT INTO Teams VALUES( 479, '9844', 'CSA-AL', '阿拉戈亚诺体育队', '阿拉戈亞諾體育隊');
INSERT INTO Teams VALUES( 480, '22489', 'Brasil de Pelotas', '布拉希尔佩洛塔斯', '布拉希爾佩洛塔斯');